### ISSUE TITLE
Fix the tree iterator issues

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1450]
TODOs:
 - [ ] [Tree iterator returns `done:false` although the value is `undefined`](https://github.com/theia-ide/theia/issues/1442)
 - [ ] [Tree iterator ignores the first node](https://github.com/theia-ide/theia/issues/1444)
 - [ ] [Tree iterator terminates too early. ](https://github.com/theia-ide/theia/issues/1448)

Will be fixed as part of #20.
