### ISSUE TITLE
[git] `git commit` and `git branch` enhancements

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1711]
- [x] [[git] support commit --amend git](#602)
- [x] [[git] Support sign off option for commits](#620)
- [x] [[git] Chronologically order the Git branches](#1519)
- [x] [[git][navigator][decorator] Adjust the Git decorator colors](#1507)
