### ISSUE TITLE
[plug-in] Languages API

### ISSUE THREAD

**Issue by evidolob** [theia-ide/theia#2341]
Provide API for [language specific editor](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages):

- [x]  [Language configuration](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7408), [getLanguages](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7068) and [`match`](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7107) methods [**[issue]**](https://github.com/theia-ide/theia/issues/2348)
- [x]  [Register a completion provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7154) [**[issue]**](https://github.com/theia-ide/theia/issues/2350)
- [x] Diagnostics: `onDidChangeDiagnostics` event, `getDiagnostics` methods and [createDiagnosticCollection](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7138) [**[issue]**](https://github.com/theia-ide/theia/issues/2351)
- [x] [Register a definition provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7194) [**[issue]**](https://github.com/theia-ide/theia/issues/2353)
- [x] [Register an implementation provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7207) [**[issue]**](https://github.com/theia-ide/theia/issues/3465)
- [x] [Register a type definition provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7220) [**[issue]**](https://github.com/theia-ide/theia/issues/3463)
- [x] [Register a hover provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7233) [**[issue]**](https://github.com/theia-ide/theia/issues/2601)
- [x] [Register a document highlight provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7246) [**[issue]**](https://github.com/theia-ide/theia/issues/3635)
- [x] [Register a document symbol provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7259) [**[issue]**](https://github.com/theia-ide/theia/issues/3200)
- [x] [Register a workspace symbol provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7271) [**[issue]**](https://github.com/theia-ide/theia/issues/3353)
- [x] [Register a reference provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7284) [**[issue]**](https://github.com/theia-ide/theia/issues/3308)
- [x] [Register a formatting provider for a document](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7310)  [**[issue]**](https://github.com/theia-ide/theia/issues/2797)
- [x] [Register a formatting provider for a document range](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7327)  [**[issue]**](https://github.com/theia-ide/theia/issues/2798)
- [x] [Register a formatting provider that works on type](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7342)  [**[issue]**](https://github.com/theia-ide/theia/issues/2799)
- [x] [Register a signature help provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7356) [**[issue]**](https://github.com/theia-ide/theia/issues/2792)
- [x] [Register a document link provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7369) [**[issue]**](https://github.com/theia-ide/theia/issues/2964)
- [x] [Register a rename provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7297) [**[issue]**](https://github.com/theia-ide/theia/issues/3861)
- [x] [Register a code lens provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7181) [**[issue]**](https://github.com/theia-ide/theia/issues/3199)
- [x] [Register a code action provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7168) [**[issue]**](https://github.com/theia-ide/theia/issues/3162)
- [x] [Register a color provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7382) [**[issue]**](https://github.com/theia-ide/theia/issues/3862)
- [x] [Register a folding range provider](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L7399)  [**[issue]**](https://github.com/theia-ide/theia/issues/3863)
- [x] [Create a file system watcher](https://github.com/Microsoft/vscode/blob/5a4eab812bd485942061f71af39f3eabc52a1035/src/vs/vscode.d.ts#L6829) [**[issue]**](https://github.com/theia-ide/theia/issues/3163)

**Comment by benoitf** [comment]
can it be closed now ?
