### ISSUE TITLE
[plug-in] Implement 'views' and 'viewsContainers' contribution points and Tree API

### ISSUE THREAD

**Issue by evidolob** [theia-ide/theia#2498]
VS Code has [views](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews) contributions.
Also [registerTreeDataProvider](https://github.com/Microsoft/vscode/blob/bf7ac9201e7a7d01741d4e6e64b5dc9f3197d97b/src/vs/vscode.d.ts#L6211) and [createTreeView](https://github.com/Microsoft/vscode/blob/bf7ac9201e7a7d01741d4e6e64b5dc9f3197d97b/src/vs/vscode.d.ts#L6219) methods should be implemented.

Sub task:

- [x] [Implement 'viewsContainers' contribution point](https://github.com/theia-ide/theia/issues/2505)
- [x] [Implement 'views' contribution point](https://github.com/theia-ide/theia/issues/2507)
- [x] [Implement `registerTreeDataProvider` and `createTreeView` methods](https://github.com/theia-ide/theia/issues/2782)

**Comment by vitaliy-guliy** [comment]
To test `views` and `views containers` add following section to package.json of plugin in `contributes` section
```javascript
        "viewsContainers": {
            "activitybar": [
                {
                    "id": "debug",
                    "title": "Debug",
                    "icon": "resources/debug.svg"
                }
            ],
            "left": [
                {
                    "id": "package-explorer",
                    "title": "Package Explorer",
                    "icon": "resources/package-explorer.svg"
                }
            ],
            "right": [
                {
                    "id": "comments",
                    "title": "Comments",
                    "icon": "resources/comments.svg"
                }
            ],
            "bottom": [
                {
                    "id": "remote",
                    "title": "Remote",
                    "icon": "resources/remote.svg"
                }
            ]
        },
        "views": {
            "package-explorer": [
                {
                    "id": "package-dependencies",
                    "name": "Package Dependencies"
                },
                {
                    "id": "package-outline",
                    "name": "Package Outline"
                }
            ],
            "comments": [
                {
                    "id": "ann-comments",
                    "name": "Anna's Comments"
                },
                {
                    "id": "sun-comments",
                    "name": "Sun's Comments"
                },
                {
                    "id": "yevhen-comments",
                    "name": "Yevhen's Comments"
                }
            ],
            "remote": [
                {
                    "id": "remote-terminal",
                    "name": "Remote terminal"
                }
            ]
        }
```
