### ISSUE TITLE
Extension Mechanism

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#28]
Theia should be extendable in the following ways.
 - [x] Both the frontend and the backend should be extendable
 - [x] To allow maximum flexibility we will allow extensions to run in the main processes and access everything. Defining APIs and their lifecycle is a separate topic.
 - [x] a user should be able to install and uninstall an extension at runtime 

At the core of Theia we use dependency injection (inversify) to contribute functionality to existing hooks and also to provide new hooks. A plugin should contribute an `inversify` module, that is then just added on start up.

**Comment by hexa00** [comment]
Just to document a discussion we had with @svenefftinge we could have a first step where the extensions are specified in a config file and the app is manually recompiled.

This would make the development of extensions possible with the packaging we ultimately want with less of an effort than the full registry solution.

**Comment by akosyakov** [comment]
Some npm packages that can be useful:
- [nodemon](https://github.com/remy/nodemon) is often used for the auto server restarting
- [pm2](https://github.com/Unitech/pm2) seems to be very popular for all auto restarting, clustering, logging, monitoring and so on

**Comment by akosyakov** [comment]
I am going to use [npms](https://api-docs.npms.io/) to look up packages instead of `npm search` and http://npmsearch.com/. `npm search` fails to provide up to date information and `npmsearch.com` returns everything that matches at least one of search criteria.

**Comment by akosyakov** [comment]
Confirmed by npmjs support that there is a delay about 24h in search API + advises how to index ourself: https://github.com/npm/registry/issues/198#issuecomment-319213770

I will still go with npms since it looks like they already do indexing but in the long run we can look into suggested indexing alternatives.

**Comment by svenefftinge** [comment]
Fixed with #391
