### ISSUE TITLE
Keyboard Shortcuts Widget - Additional Features

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#2939]
`keybindings-widget` additional functionality and improvements:

- [x] Add `iconClass` and `caption` to `keybindings-widget` #3180
- [x] Add `context` to the `keymaps.json` file. #3237
- [x] Add tooltip for each table entry #3206
- [x] Disable ability to revert keybinding for keybindings which are not `User` scope
- [x] Display `keymaps.json` as a side panel for manual editing (currently in review) #3133
- [x] Dispose the widget properly #3106
- [x] Fix `containsKeybinding` return logic #2974
- [x] Fix debounce declaration #3060
- [x] Fix react-key error #3065
- [x] Static search bar
- [x] Fuzzy search highlighting #2893
- [x] Handle setting foucs on `keybindings-widget` search field when activated #3105
- [x] Handle validating keybinding when old and new values match #3213
- [x] Scope column #3222
- [x] Refactor `removeKeybinding` button to `resetKeybinding` #3259
- [x] Remove `removeKeybinding` button for keybindings which have yet to be updated #3239
(Removes the `MessageService` which told users an unedited keybinding cannot be removed)
- [x] Reset keybinding (ability to reset/remove keybinding) #2893
