### ISSUE TITLE
[plug-in] Implement VS Code Built-in Commands 

### ISSUE THREAD

**Issue by vparfonov** [theia-ide/theia#4050]
Built-in Commands used i VS Code Extensions widely, so for beeter support in as Theia Plugin we need to cover such command as is it possible.
List of command described here: 
https://code.visualstudio.com/api/references/commands

**Comment by akosyakov** [comment]
Whoever will do it, please check how each command is implemented in VS Code. Sometimes it is just calling another command which can be already available via Monaco. In this case we don't need to expose any internal Monaco API or copy code from VS Code, but just use our command registry and call delegate command.

**Comment by tsmaeder** [comment]
I guess the commands should be registered here: https://github.com/theia-ide/theia/blob/master/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L35

**Comment by benoitf** [comment]
I'm not finding anymore the issue but I'm pretty sure to have read that @svenefftinge wanted to align all the names of commands to match VS Code one (I suppose all the names that are not prefixed by `vscode.`)

here is another list as well:
https://code.visualstudio.com/docs/getstarted/keybindings#_navigation

so I would suppose `vscode.` commands should go as @tsmaeder said but for the others it should either rename original name (breaking change..) or currently add the alias but in theia command contribution, not only in `vscode`.

**Comment by akosyakov** [comment]
> I'm not finding anymore the issue but I'm pretty sure to have read that @svenefftinge wanted to align all the names of commands to match VS Code one (I suppose all the names that are not prefixed by vscode.)

please see https://github.com/theia-ide/theia/pull/4193#issuecomment-459224709

cc @svenefftinge

**Comment by akosyakov** [comment]
> here is another list as well:
https://code.visualstudio.com/docs/getstarted/keybindings#_navigation

👍 

related: https://github.com/theia-ide/theia/issues/4204

**Comment by vinokurig** [comment]
It would be great to have next commands that are needed for the [VsCode Emacs Keymap extension](https://marketplace.visualstudio.com/items?itemName=lfs.vscode-emacs-friendly):
- [ ] lineBreakInsert - Insert Enter
- [ ] workbench.action.openRecent - Open recent command
- [ ] workbench.action.splitEditorDown - Split editor horizontal
- [ ] workbench.action.splitEditorRight - Split editor vertical
- [ ] workbench.action.toggleEditorGroupLayout - Toggle split layout (vertical to horizontal)
- [ ] workbench.action.navigateEditorGroups  - Focus other split editor

see https://github.com/eclipse-theia/theia/pull/6625

**Comment by vinokurig** [comment]
- [ ] editor.action.reindentselectedlines 

Needed for the [VsCode Vim extension](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) see: https://github.com/eclipse-theia/theia/pull/6687

**Comment by tomer-epstein** [comment]
Is there a plan to imlement 'vscode.openFolder' soon?
* [ ]  vscode.openFolder - Open a folder or workspace in the current window or new window depending on the newWindow argument.

**Comment by akosyakov** [comment]
@tomer-epstein PRs are welcomed, it should not be hard to implement, there is `WorkspaceService .open` API which accepts an URI of a folder to open and a second options with an argument whether a window should be preserved. One has to add a new command in [PluginVscodeCommandsContribution](https://github.com/eclipse-theia/theia/blob/15af8552a7223922fa59db4a2177d8b570d158fa/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L58).

**Comment by tavoda** [comment]
After installing VSCode VIM plugin from https://marketplace.visualstudio.com/items?itemName=vscodevim.vim, I'm getting following error after pressing CTRL+F:

> TaskQueue: Error running task. Failed to handle key=<C-f>. Command with id 'editorScroll' is not registered.. for VSCode VIM extension 


Is editorScroll still not implemented?

**Comment by akosyakov** [comment]
@tavoda It should be, we receive directly from Monaco editor. Do you use master? It would be worth to file a separate issue.

**Comment by akosyakov** [comment]
Let's keep this issue as a live document to track missed commands coverage. One can file individual issues as well, but please update the first comment of this issue.
