### ISSUE TITLE
Improve Developing.md

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#440]
It would be nice:
- [x] put https://github.com/theia-ide/theia/blob/master/doc/Developing.md#tldr at the beginning
- [x] add some kind of index (a table of contents) right now is not clear how parts are related
- [x] remove `--unsafe-perm` and add it to the troubleshooting part: https://github.com/theia-ide/theia/issues/311
- [x] explain the repo structure: https://github.com/theia-ide/theia/issues/359#issuecomment-319008318
- [x] detail what running `yarn` in the root does: https://github.com/theia-ide/theia/blob/master/doc/Developing.md#build-core-extensions-and-examples-packages + https://github.com/theia-ide/theia/issues/359#issuecomment-319008318
- [x] use proper brand names: VSCode and not vscode, JavaScript not Javascript, Node.js and not nodejs
- [x] mention in the prerequisites that node version 6+ is required - https://github.com/theia-ide/theia/issues/440#issuecomment-325952376 + https://github.com/theia-ide/theia/issues/440#issuecomment-326579581

**Comment by pierregoutagny** [comment]
Hi, I just wanted to say I'm working on this. This is my first time contributing to a GitHub project BTW.

**Comment by akosyakov** [comment]
@pierregoutagny cool! thanks for looking into it. please don't try to fix everything at once, point by point will be better

**Comment by marcdumais-work** [comment]
@akosyakov another small improvement suggestion to perhaps add to the list: mention in the prerequisites that node version 6+ is required. On the latest Ubuntu LTS (16.04), node 4 is installed from the official Canonical repository, and that version doesn't work with Theia.

**Comment by pierregoutagny** [comment]
@akosyakov I'm quite confused about `--unsafe-perm`. Should we say that this flag is only useful when the user has root privileges? If so, does that mean that the troubleshooting should have a section about the `cannot run in wd` error message that recommends to either use the flag when root, or simply not to install as root? (https://github.com/theia-ide/theia/issues/266#issuecomment-313335250)

**Comment by hexa00** [comment]
Yes that would be great! There's even an issue about it see: #311

**Comment by rcjsuen** [comment]
The file currently mentions that Node.js 8.x doesn't build but that's no longer the case according to 37f0cecdb7b53e86158fd3b692a1cd9bd78310dc so that needs to be updated as well.

**Comment by akosyakov** [comment]
Resolved by https://github.com/theia-ide/theia/pull/442

@pierregoutagny thanks again
